version: '3.3'
services:
  
  
  elden_db_26:
    image: mysql:8.0.28
    restart: always
    container_name: "elden_db_26"
    environment:
      MYSQL_DATABASE: 'db_elden_music'
      MYSQL_USER: 'elden'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'rootroot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 9026:3306
    networks:
      - our-library-net
    volumes:
      - /home/luis_pena/proyecto-final-musica/mysql:/var/lib/mysql
      - /home/luis_pena/proyecto-final-musica/Elden-Music-Proyecto-Final/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  
  elden_back_26:
    build: 
      context: .
      dockerfile: Dockerfile.back
    container_name: "elden_back_26"
    command: npm run start
    networks:
      - our-library-net
    volumes:
      - ./elden-backend:/usr/app/elden-server
      - /usr/app/elden-server/node_modules
    ports:
      - "11026:8000"
    depends_on:
      - elden_db_26
    environment:
      - "MSQL_DB=db_elden_music"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=rootroot"
      - "MYSQL_HOST=elden_db_26"
      - "MYSQL_PORT=3306"


  elden_front_26:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: "elden_front_26"
    command: npm run start
    networks:
      - our-library-net
    volumes:
      - ./elden-front:/usr/app/elden-front
      - /usr/app/elden-front/node_modules
    ports:
      - "10026:3000"
    depends_on:
      - elden_back_26


networks:
  our-library-net:
    external: true
    driver: bridge